import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, Award, Clock3, GraduationCap, Heart, Music2, Star, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell, SectionHeading } from "@/components/kryso-site";
import { courses, testimonials } from "@/data/catalog";

export const Route = createFileRoute("/academy")({ head: () => ({ meta: [
  { title: "Music Classes & Courses | Kryso Music Academy, Pune" }, { name: "description", content: "Explore guitar, piano, vocals, violin, tabla and more at Kryso Music Academy in Pune." },
  { property: "og:title", content: "Learn Music at Kryso Music Academy" }, { property: "og:description", content: "Music lessons for curious beginners and growing musicians in Pune." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Academy });

const perks = [
  { icon: Award, title: "Experienced teachers", text: "Learn with working musicians who love to teach." },
  { icon: Heart, title: "A friendly room", text: "Start at your own pace, with no experience needed." },
  { icon: UsersRound, title: "Personal attention", text: "Small group and one-to-one learning, your way." },
  { icon: Music2, title: "Make music together", text: "Practice sessions and chances to play for an audience." },
  { icon: GraduationCap, title: "A real foundation", text: "Build practical skills as well as musical understanding." },
  { icon: Clock3, title: "Timings that fit", text: "Ask about lesson times that work with your week." },
];

function Academy() {
  const [review, setReview] = useState(0);
  return <SiteShell>
    <section className="bg-secondary text-secondary-foreground"><div className="page-shell grid gap-12 py-16 md:grid-cols-[1.1fr_.9fr] md:items-center md:py-20"><div><p className="eyebrow">Kryso Music Academy · Pune</p><h1 className="mt-4 font-display text-4xl font-extrabold leading-tight sm:text-5xl">A little music can change <span className="text-primary">a lot.</span></h1><p className="mt-5 max-w-xl leading-7 text-secondary-foreground/70">We make learning music welcoming, practical and full of those small moments that make you want to keep playing.</p><Button className="mt-8 h-12 rounded-full px-6 font-bold" onClick={() => window.dispatchEvent(new CustomEvent("kryso:open-enquiry"))}>Find your class <ArrowUpRight size={17}/></Button></div><div className="grid grid-cols-2 gap-3">{[{ word: "Start", line: "with the basics" }, { word: "Explore", line: "your own sound" }, { word: "Practice", line: "with good people" }, { word: "Perform", line: "when you're ready" }].map((item, i) => <div key={item.word} className={`min-h-32 p-5 ${i === 1 || i === 2 ? "bg-primary text-primary-foreground" : "bg-secondary-foreground/10"}`}><span className="font-display text-2xl font-extrabold">{item.word}</span><p className="mt-2 text-sm opacity-75">{item.line}</p></div>)}</div></div></section>
    <section className="page-shell section-space grid gap-12 lg:grid-cols-2"><div><SectionHeading label="Our approach" title="Good teaching. Great music. No pressure."/><p className="mt-5 leading-7 text-muted-foreground">Kryso is a place for curious people of all ages to slow down, listen, and learn. Our teachers meet you where you are—whether you have never touched an instrument or you're ready to take your playing further.</p><p className="mt-4 leading-7 text-muted-foreground">We believe music belongs to everyone. Every lesson pairs a thoughtful foundation with time to play songs you actually love.</p></div><div className="grid content-start gap-6 border-l-2 border-primary pl-6"><div><p className="eyebrow">Our mission</p><p className="mt-2 font-display text-xl font-bold">Make music education joyful, accessible and personal.</p></div><div><p className="eyebrow">Our vision</p><p className="mt-2 font-display text-xl font-bold">A community where everyone feels at home with music.</p></div><div><p className="eyebrow">In the studio</p><p className="mt-2 leading-7 text-muted-foreground">A bright, welcoming practice space, instruments to explore, and friendly guidance whenever you need it.</p></div></div></section>
    <section className="border-y border-border bg-card"><div className="page-shell section-space"><SectionHeading label="A good place to learn" title="The right kind of support." text="Music lessons built around people—not just pages in a book."/><div className="mt-10 grid gap-x-10 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">{perks.map(({ icon: Icon, title, text }) => <div key={title} className="border-t border-border pt-5"><Icon size={20} className="text-primary"/><h2 className="mt-4 font-display text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="page-shell section-space"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading label="Choose a course" title="What would you love to play?" text="One-to-one and small-group options available. All ages welcome."/><span className="pb-1 text-xs font-semibold text-muted-foreground">Beginner · Intermediate · Advanced</span></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{courses.map((course) => <article key={course.id} className="border border-border bg-card p-6"><div className="flex items-center justify-between"><div className="grid size-12 place-items-center rounded-full bg-accent font-display text-xl text-primary">{course.icon}</div><span className="text-xs font-semibold text-muted-foreground">{course.level}</span></div><h2 className="mt-5 font-display text-xl font-bold">{course.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{course.description}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4 text-xs"><div><span className="block text-muted-foreground">Duration</span><span className="mt-1 block font-bold">{course.duration}</span></div><div><span className="block text-muted-foreground">Monthly fees</span><span className="mt-1 block font-bold">₹{course.fees.toLocaleString("en-IN")}</span></div></div><p className="mt-4 text-xs text-muted-foreground">With {course.instructor}</p><Button onClick={() => window.dispatchEvent(new CustomEvent("kryso:open-enquiry"))} variant="outline" className="mt-5 h-10 w-full rounded-full">Ask about this class <ArrowRight size={15}/></Button></article>)}</div></section>
    <section className="bg-accent/35"><div className="page-shell section-space grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-center"><div><SectionHeading label="From our students" title="The best part is making music together." text="A few words from people who've started their own musical journeys with us."/><div className="mt-7 flex gap-2"><Button variant="outline" size="icon" className="rounded-full" aria-label="Previous review" onClick={() => setReview((review + testimonials.length - 1) % testimonials.length)}>←</Button><Button variant="outline" size="icon" className="rounded-full" aria-label="Next review" onClick={() => setReview((review + 1) % testimonials.length)}>→</Button></div></div><div className="bg-card p-7 sm:p-10"><div className="flex gap-1 text-primary">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={15} fill="currentColor"/>)}</div><p className="mt-5 font-display text-xl font-semibold leading-8">“{testimonials[review]?.text}”</p><div className="mt-7 flex items-center gap-3 border-t border-border pt-5"><span className="grid size-11 place-items-center rounded-full bg-accent font-display font-bold text-primary">{testimonials[review]?.name.charAt(0)}</span><div><p className="font-bold">{testimonials[review]?.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{testimonials[review]?.course} student</p></div></div></div></div></section>
    <section className="page-shell py-16"><div className="grid gap-6 sm:grid-cols-4">{["In the practice room", "Learning together", "Sharing a first song", "Music in the making"].map((caption, i) => <div key={caption} className={`grid aspect-[4/3] place-items-end p-4 ${["bg-accent/60", "bg-muted", "bg-secondary text-secondary-foreground", "bg-primary/20"][i]}`}><span className="text-xs font-semibold">{caption}</span></div>)}</div></section>
    <section className="bg-secondary text-secondary-foreground"><div className="page-shell flex flex-wrap items-center justify-between gap-6 py-12"><div><p className="eyebrow">Ready when you are</p><h2 className="mt-2 font-display text-2xl font-extrabold">Your next favourite thing could be a song.</h2></div><Button onClick={() => window.dispatchEvent(new CustomEvent("kryso:open-enquiry"))} className="h-12 rounded-full px-6 font-bold">Enquire about classes <ArrowUpRight size={17}/></Button></div></section>
  </SiteShell>;
}