import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Clock3, Mail, MapPin, Phone, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { SiteShell, SectionHeading } from "@/components/kryso-site";
import { saveEnquiry } from "@/lib/kryso-storage";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Kryso Music Academy | Pune" }, { name: "description", content: "Talk to Kryso Music Academy about music classes, instruments and visiting us in Pune, Maharashtra." },
  { property: "og:title", content: "Contact Kryso Music Academy" }, { property: "og:description", content: "Get in touch about music classes and instruments in Pune." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Contact });

function Contact() {
  const [sent, setSent] = useState(false);
  return <SiteShell><section className="bg-secondary text-secondary-foreground"><div className="page-shell py-16 sm:py-20"><p className="eyebrow">We'd love to hear from you</p><h1 className="mt-3 font-display text-4xl font-extrabold sm:text-5xl">Let's talk <span className="text-primary">music.</span></h1><p className="mt-4 max-w-lg leading-7 text-secondary-foreground/70">Questions about a class? Looking for an instrument? Drop us a note or give us a call.</p></div></section>
    <section className="page-shell section-space grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading label="Find us in Pune" title="Say hello, or come say hi."/><div className="mt-8 grid gap-6">{[{ Icon: MapPin, name: "Visit", info: "Pune, Maharashtra, India" }, { Icon: Phone, name: "Call us", info: "+91 87678 28945", href: "tel:+918767828945" }, { Icon: Phone, name: "Or reach", info: "+91 97673 78750", href: "tel:+919767378750" }, { Icon: Mail, name: "Email", info: "krysomusicacademy@gmail.com", href: "mailto:krysomusicacademy@gmail.com" }].map(({ Icon, name, info, href }) => <div className="flex gap-4" key={name}><span className="grid size-10 shrink-0 place-items-center rounded-full bg-accent text-primary"><Icon size={18}/></span><div><p className="text-xs font-bold uppercase text-muted-foreground">{name}</p>{href ? <a href={href} className="mt-1 block font-semibold hover:text-primary">{info}</a> : <p className="mt-1 font-semibold">{info}</p>}</div></div>)}</div><div className="mt-8 flex min-h-44 flex-col justify-between bg-muted p-5"><span className="flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground"><MapPin size={15}/> Pune, Maharashtra</span><div><p className="font-display text-xl font-bold">A place for music, near you.</p><p className="mt-1 text-sm text-muted-foreground">Get in touch for the exact location and visiting hours.</p></div></div><p className="flex items-center gap-2 text-sm text-muted-foreground"><Clock3 size={16}/> Please call ahead to arrange a visit.</p></div>
      <div className="border border-border bg-card p-6 sm:p-9"><p className="eyebrow">Send a message</p><h2 className="mt-2 font-display text-2xl font-extrabold">What’s on your mind?</h2><p className="mt-2 text-sm text-muted-foreground">Share a little, and we’ll take it from there.</p>{sent ? <div role="status" className="mt-8 grid justify-items-center bg-accent/60 p-10 text-center"><CheckCircle2 size={35} className="text-primary"/><p className="mt-3 font-display text-xl font-bold">Thanks for reaching out.</p><p className="mt-2 text-sm text-muted-foreground">Your message has been received in this demo.</p><Button variant="outline" className="mt-5 rounded-full" onClick={() => setSent(false)}>Send another message</Button></div> : <form className="mt-7 grid gap-4" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); saveEnquiry({ kind: "contact", name: String(data.get("name") ?? ""), phone: String(data.get("phone") ?? ""), email: String(data.get("email") ?? ""), message: String(data.get("message") ?? "") }); setSent(true); }}><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold">Name<Input name="name" required placeholder="Your name"/></label><label className="grid gap-1.5 text-sm font-semibold">Phone<Input name="phone" required type="tel" placeholder="+91"/></label></div><label className="grid gap-1.5 text-sm font-semibold">Email<Input name="email" required type="email" placeholder="you@example.com"/></label><label className="grid gap-1.5 text-sm font-semibold">Message<Textarea name="message" required rows={5} placeholder="Tell us how we can help"/></label><Button type="submit" className="h-11 rounded-full font-bold">Send message <Send size={16}/></Button><p className="text-center text-xs text-muted-foreground">Demo form · saved in your browser for the admin demo.</p></form>}</div>
    </section></SiteShell>;
}