import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, Guitar, Music2, Star } from "lucide-react";
import heroImage from "@/assets/kryso-hero.jpg";
import { Button } from "@/components/ui/button";
import { SiteShell, SectionHeading } from "@/components/kryso-site";
import { courses, products } from "@/data/catalog";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Kryso Music Academy | Learn Music and Enjoy Music" },
    { name: "description", content: "Find your rhythm at Kryso Music Academy in Pune. Explore joyful music classes and thoughtfully chosen instruments." },
    { property: "og:title", content: "Kryso Music Academy — Learn Music and Enjoy Music" },
    { property: "og:description", content: "Find your rhythm. Music lessons and instruments in Pune, Maharashtra." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: HomePage,
});

function HomePage() {
  return <SiteShell>
    <section className="relative isolate min-h-[640px] overflow-hidden bg-secondary text-secondary-foreground md:min-h-[690px]">
      <img src={heroImage} width={1536} height={1024} alt="Guitar, piano, drums and violin in a warmly lit music studio" className="absolute inset-0 -z-20 h-full w-full object-cover object-[62%_center]"/>
      <div className="absolute inset-0 -z-10 bg-linear-to-r from-secondary via-secondary/85 to-secondary/15"/>
      <div className="page-shell grid min-h-[640px] items-center py-20 md:min-h-[690px]">
        <div className="max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full border border-secondary-foreground/20 bg-secondary/40 px-4 py-2 text-xs font-semibold"><span className="size-2 rounded-full bg-primary"/> MUSIC, WITH ROOM TO GROW</div>
          <h1 className="mt-7 font-display text-5xl font-extrabold leading-[1.06] sm:text-6xl lg:text-7xl">Learn music.<br/><span className="text-primary">Enjoy music.</span></h1>
          <p className="mt-6 max-w-xl text-base leading-7 text-secondary-foreground/75 sm:text-lg">Find your rhythm at Kryso Music Academy. Learn from passionate teachers, discover your sound, and bring home an instrument you’ll love.</p>
          <div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="h-12 rounded-full px-6 font-bold"><Link to="/academy">Explore classes <ArrowRight size={17}/></Link></Button><Button asChild size="lg" variant="outline" className="h-12 rounded-full border-secondary-foreground/30 bg-secondary/30 px-6 text-secondary-foreground hover:bg-secondary-foreground/10 hover:text-secondary-foreground"><Link to="/music">Shop instruments <ArrowUpRight size={17}/></Link></Button></div>
          <div className="mt-12 flex items-center gap-5 border-t border-secondary-foreground/15 pt-6"><div className="flex -space-x-2">{["A", "R", "S"].map((person) => <span key={person} className="grid size-9 place-items-center rounded-full border-2 border-secondary bg-primary/80 text-xs font-bold text-secondary">{person}</span>)}</div><div><p className="flex items-center gap-1 text-sm font-bold"><Star size={14} className="fill-primary text-primary"/> 4.9 <span className="font-normal text-secondary-foreground/65">from our music community</span></p><p className="mt-0.5 text-xs text-secondary-foreground/55">Good music starts with good people.</p></div></div>
        </div>
      </div>
      <span className="absolute bottom-6 right-8 hidden text-xs font-semibold uppercase tracking-[.12em] text-secondary-foreground/45 lg:block">Pune · Maharashtra</span>
    </section>
    <section className="page-shell section-space grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><SectionHeading label="A place to begin" title="Make music part of your everyday." text="Whether you're picking up an instrument for the first time or finding your way back to one, there's a seat—and a song—with your name on it."/><Link to="/academy" className="mt-6 inline-flex items-center gap-2 font-bold text-primary hover:gap-3">Meet the academy <ArrowRight size={17}/></Link></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-border bg-border">{[{ number: "9", caption: "instruments to learn" }, { number: "All", caption: "ages welcome" }, { number: "1:1", caption: "personal attention" }, { number: "100%", caption: "music, all heart" }].map((fact) => <div key={fact.caption} className="bg-card p-7 sm:p-9"><p className="font-display text-3xl font-extrabold text-primary">{fact.number}</p><p className="mt-2 text-sm text-muted-foreground">{fact.caption}</p></div>)}</div></section>
    <section className="border-y border-border bg-card"><div className="page-shell section-space"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading label="Find your sound" title="A class for every kind of curious." text="Small steps, great songs, and the joy of getting a little better every week."/><Link to="/academy" className="hidden items-center gap-2 pb-1 font-bold hover:text-primary sm:flex">All classes <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{courses.slice(0,3).map((course, index) => <Link key={course.id} to="/academy" className="group border-t-2 border-border p-6 transition-colors hover:border-primary hover:bg-background"><div className={`grid size-12 place-items-center rounded-full ${index === 1 ? "bg-secondary text-secondary-foreground" : "bg-accent text-primary"}`}><span className="font-display text-xl">{course.icon}</span></div><div className="mt-6 flex items-center justify-between"><h3 className="font-display text-xl font-bold">{course.name}</h3><ArrowUpRight size={18} className="text-muted-foreground transition-colors group-hover:text-primary"/></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{course.description}</p><p className="mt-5 text-xs font-semibold text-muted-foreground">{course.duration} <span className="px-1.5 text-primary">·</span> from ₹{course.fees.toLocaleString("en-IN")}/month</p></Link>)}</div></div></section>
    <section className="page-shell section-space"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading label="The music shop" title="A good instrument changes everything." text="A few of our favourites, chosen to help you find your sound."/><Link to="/music" className="inline-flex items-center gap-2 pb-1 font-bold hover:text-primary">Visit the shop <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map((product, index) => <Link to="/music" key={product.id} className="group overflow-hidden border border-border bg-card"><div className={`relative grid aspect-[4/3] place-items-center ${index % 2 ? "bg-muted" : "bg-accent/45"}`}><div className="grid size-24 place-items-center rounded-full bg-background shadow-sm transition-transform group-hover:scale-105"><Guitar size={40} strokeWidth={1.2} className="text-primary"/></div><span className="absolute left-3 top-3 rounded-full bg-background px-3 py-1 text-[10px] font-bold uppercase">{product.tag}</span></div><div className="p-4"><p className="text-xs text-muted-foreground">{product.category}</p><h3 className="mt-1 font-display font-bold">{product.name}</h3><div className="mt-3 flex justify-between"><span className="font-bold">₹{product.price.toLocaleString("en-IN")}</span><span className="flex items-center gap-1 text-xs"><Star size={13} className="fill-primary text-primary"/>{product.rating}</span></div></div></Link>)}</div></section>
    <section className="bg-accent/40"><div className="page-shell grid gap-8 py-16 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow">Your first note is closer than you think</p><h2 className="mt-3 font-display text-3xl font-extrabold">Come as you are. Leave a little more musical.</h2><p className="mt-3 text-muted-foreground">Curious about a class? Tell us what you have in mind.</p></div><Button onClick={() => window.dispatchEvent(new CustomEvent("kryso:open-enquiry"))} className="h-12 rounded-full px-6 font-bold">Talk to our team <ArrowUpRight size={17}/></Button></div></section>
  </SiteShell>;
}